.TH G64 3 "Dec. 15, 2020" "version 0"

.SH NAME
G64 - General\-purpose utility library

.SH SYNOPSIS
#include <G64/G64.h>

.SH DESCRIPTION
G64 is a general-purpose utility library created by DreamingWarlord.
It was made to avoid having to write code for essential things like
vectors, files, lexical analysis, hash maps, profiling or strings.
An earlier version of G64 is called
.BI "LCUL (Lightweight C Utility Library)."
.PP
LCUL was a small library consisting of 181 lines of code for dynamic
arrays, maps and functions for loading files. It was uploaded to github
on May 24, 2020. Exact creation date is unknown.
.PP
First mention of G64 is in July 2020 and that is accepted to be the
creation date of the library. First use of
.BI git
was in November. That is also when a Makefile was added to the project.
